### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by H-Park** [wuhuikai/MSC#1]
Recreating the database with a min_mrr flag of 4000, and there is a runtime error in parse_replay_info.py

You need to call FLAGS(sys.argv) after the flags.DEFINE methods.

**Comment by wuhuikai** [comment]
There isn't  a flag min_mmr in parse_replay_info.py but in [preprocess.py](https://github.com/wuhuikai/MSC/blob/446f1d810711e7cc559f4493655a0731024a40ae/preprocess/preprocess.py#L29). We do not need to call FLAGS(sys.argv) explicitly, because app.run() does it.

**Comment by H-Park** [comment]
What version of gflags are you using?

**Comment by wuhuikai** [comment]
@TuringsEgo python_gflags == 3.1.1

**Comment by H-Park** [comment]
I think the update of PySC2 is the root of this error. They removed app from pysc2.lib 

https://github.com/deepmind/pysc2/commit/f2f96c08c32ea92fa60485cc6d7307bc17c1c6db

Prior to this commit, you are correct in that it called FLAGS(sys.argv) for you. 

Are you going support the newest version of PySC2 in the future?

**Comment by wuhuikai** [comment]
@TuringsEgo You're right. They removed app from pysc2.lib. I'll write my own app and replace it.

**Comment by emiasims** [comment]
You can use `absl` as pysc2 does. The app() calls will need to be given main as an arg, and instead of gflags `from absl import flags` seems to be working for me. Don't need to write one.

**Comment by wuhuikai** [comment]
@matthsims Yes, you're right.

**Comment by wuhuikai** [comment]
Solved in #4.
