### ISSUE TITLE
cannot from pysc2.lib import FUNCTIONS

### ISSUE THREAD

**Issue by HaibeiZhu** [wuhuikai/MSC#10]
Hi, thank you for implementing this repo!

Line 13 of the "parse_replay/sample_actions.py" is "from pysc2.lib import FUNCTIONS". However, such an import failed. I think it may be caused by DeepMind updated the pysc2.lib.

I appreciate it if you could check and fix this issue. Thanks

**Comment by wuhuikai** [comment]
Changing `from pysc2.lib import FUNCTIONS` to `from pysc2.lib.actions import FUNCTIONS` might work.
However, this repo is not actively maintained. So, I suggest using the old version of `pysc2`.
Otherwise, you'll need to wait for a long time before this repo is updated to the latest `pysc2`.
