### ISSUE TITLE
About global features vector

### ISSUE THREAD

**Issue by 1Wayne1** [wuhuikai/MSC#11]
I've download your [global features vector](https://drive.google.com/file/d/0Bybnpq8dvwudNUVOX1FCWnZoSGM/view) consist of lots of files postfix ".npz". There are 5 subdatasets in each file when I load them and I can't understand it with your describe of "Global Features Vector". It should be a matrix F(T,M) as you say, but I can't correspond which I download with the matrix F(T,M).

I'm a graduate student. Looking forward to your reply.

**Comment by wuhuikai** [comment]
Each `.npz` contains a matrix.
