### ISSUE TITLE
Failed to use json.load to open the file 

### ISSUE THREAD

**Issue by paopjian** [wuhuikai/MSC#12]
with open('a.SC2Replay') as f:
    json.load(f)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xac in position 60: illegal multibyte sequence
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 60: invalid start byte

I tried many times, but still fail to read the replay in json

**Comment by wuhuikai** [comment]
replay can not be loaded by json.
