### ISSUE TITLE
Action parsing

### ISSUE THREAD

**Issue by dai-dao** [wuhuikai/MSC#5]
Hi,

To read the action from the replays, is there a way to read the action arguments as well? For now it's just the action ID and no arguments.

Thanks

**Comment by wuhuikai** [comment]
Yes, the action we extract [here](https://github.com/wuhuikai/MSC/blob/60e70b9418ed31c28fd66675125c6a20f3c04721/parse_replay/extract_actions.py#L103) contains all the [information](https://github.com/Blizzard/s2client-proto/blob/a026e018f1a37b2021414248b8db24794928d917/s2clientprotocol/sc2api.proto#L570) you need.

**Comment by dai-dao** [comment]
Thank you very much. Just one more question. I'm parsing the actions the "Hard way", by running the script ```python extract_actions.py```, and am inspecting the output of the script. 

Why are there multiple actions per frame? I'm not sure what that means, I thought it can only issue 1 action per frame. Could you please advice?

**Comment by wuhuikai** [comment]
The actions are extracted every 8 frames not every frame.

**Comment by dai-dao** [comment]
Have you guys tried training the network on every action? Including micro-management / combat? besides just the macro tasks. 

I assume the dataset includes an entire game from start to finish.

**Comment by dai-dao** [comment]
The below code is from extract_action.py:

```
def process_replay(self, controller, replay_data, map_data, player_id, race, replay_path):
        controller.start_replay(sc_pb.RequestStartReplay(
            replay_data=replay_data,
            map_data=map_data,
            options=interface,
            observed_player_id=player_id))

        save_folder = os.path.join(FLAGS.save_path, race)
        actions = []
        controller.step()
        while True:
            obs = controller.observe()
            actions.append([MessageToJson(a) for a in obs.actions])

            if obs.player_result:
                with open(os.path.join(save_folder, '{}@{}'.format(
                        player_id, os.path.basename(replay_path))), 'w') as f:
                    json.dump(actions, f)
                return
            controller.step(FLAGS.step_mul)
```

I notice that your controller is stepping by ```step_mul``` times each iteration. Does ```obs.actions``` return all the actions that was executed during ```step_mul``` frames? So if I want to extract every action along with each frame that it was executed I should just step by 1 each time?

Thanks for your advice

**Comment by wuhuikai** [comment]
It returns all the actions that were executed during `step_mul` frames. If you want to extract every action along with each frame, you should set `step_mul` to `1`. But I think `8` is also OK for your task.
