### ISSUE TITLE
Get primitive action id from dataset

### ISSUE THREAD

**Issue by dai-dao** [wuhuikai/MSC#7]
Hi, thanks for making this repo and release your macro dataset. In your dataset for example Terran, the action space is limited to 75 actions, 0-74. How can I map it back to pysc2's original action space? (0-523)

Thank you so much

**Comment by wuhuikai** [comment]
Yes, you can. See **action_id** in [this file](https://github.com/wuhuikai/MSC/blob/master/parsed_replays/Stat/Terran_human.json) for an example.

**Comment by dai-dao** [comment]
Thank you. Solved
