### ISSUE TITLE
Multiprocessing breaks flags when parsing replay info

### ISSUE THREAD

**Issue by fofferhorn** [wuhuikai/MSC#8]
Hi,

When I try to parse replay info using the given file parse_replay_info.py I get the error seen below.

```
Traceback (most recent call last):
  File "...\Python36\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "...\MSC\preprocess\parse_replay_info.py", line 44, in run
    with self.run_config.start() as controller:
  File "...\Python36\lib\site-packages\pysc2\run_configs\platforms.py", line 102, in start
    version = version or FLAGS.sc2_version
  File "...\Python36\lib\site-packages\absl\flags\_flagvalues.py", line 488, in __getattr__
    raise _exceptions.UnparsedFlagAccessError(error_message)
absl.flags._exceptions.UnparsedFlagAccessError: Trying to access flag --sc2_version before flags were parsed.
```

As far as I can tell the error occurs because the flags from absl aren't passed to the child processes spawned to parse the replay info. 

One temporary and tideous fix is to go into all the files used an hard code all the values instead of using the flag values. If someone else has a better fix, please let me know.

I don't know if it makes a difference, but my platform is Windows 10. 

EDIT: I don't get the same error in Linux so the issue seems to be Windows specific.

**Comment by wuhuikai** [comment]
I have no access to `Windows` OS, all the programs are tested on `Ubuntu 16.04 LTS`. For your problem, one possible reason is that the version of `pysc2` is not correct. You can refer to #1 for more information.
