### ISSUE TITLE
Could not open initData for the replay

### ISSUE THREAD

**Issue by nidao66** [wuhuikai/MSC#9]
When I run the parse_replay_info.py, I get the following error:
pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseReplayInfo.Error.ParsingError: 'Could not open initData for the replay: C:\Users\DCS\AppData\Local\Temp\StarCraft II\TempReplayInfo~01.SC2Replay'
Could you please tell me how to fix this? Thank you.

**Comment by wuhuikai** [comment]
It's an issue casued by SC2API. Please open an issue in SC2API's GitHub.

**Comment by GoingMyWay** [comment]
> When I run the parse_replay_info.py, I get the following error:
> pysc2.lib.remote_controller.RequestError: SC2APIProtocol.ResponseReplayInfo.Error.ParsingError: 'Could not open initData for the replay: C:\Users\DCS\AppData\Local\Temp\StarCraft II\TempReplayInfo~01.SC2Replay'
> Could you please tell me how to fix this? Thank you.

@nidao66 Hi, have you fixed this issue?
